version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php-fpm
  php-fpm:
    image: php:8.3-fpm
    volumes:
      - ../:/var/www/html

