version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../:/var/www/html
    working_dir: /var/www/html
