version: '3.8'
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../:/var/www/html
      - ./php-fpm/logs/php-fpm:/var/log/php-fpm
      - ./php-fpm/logs/game1:/var/log/game1
    working_dir: /var/www/html
